// DAPUR MULIA - Complete Product Data (140+ products)
const productsData = [
    { id: 1, name: "Kue Lapis", category: "Kue Basah", price: 25000, discountPrice: 20000, image: "", rating: 4.5, reviews: 23, description: "Kue lapis legit dengan 8 lapisan warna-warni, lembut dan manis.", isNew: true, isPopular: true },
    { id: 2, name: "Kue Lumpur", category: "Kue Basah", price: 30000, discountPrice: 0, image: "", rating: 4.3, reviews: 15, description: "Kue lumpur kentang dengan topping kismis, tekstur lembut." },
    { id: 3, name: "Kue Cubit", category: "Kue Basah", price: 15000, discountPrice: 12000, image: "", rating: 4.7, reviews: 31, description: "Kue cubit mini dengan topping meses dan keju.", isPopular: true },
    { id: 4, name: "Kue Putu Ayu", category: "Kue Basah", price: 28000, discountPrice: 0, image: "", rating: 4.4, reviews: 18, description: "Kue putu ayu pandan dengan parutan kelapa." },
    { id: 5, name: "Kue Serabi", category: "Kue Basah", price: 20000, discountPrice: 17000, image: "", rating: 4.6, reviews: 27, description: "Serabi kuah kinca manis khas Sunda." },
    { id: 6, name: "Kue Ape", category: "Kue Basah", price: 18000, discountPrice: 0, image: "", rating: 4.2, reviews: 12, description: "Kue ape teflon dengan taburan gula halus." },
    { id: 7, name: "Kue Nagasari", category: "Kue Basah", price: 22000, discountPrice: 0, image: "", rating: 4.5, reviews: 20, description: "Nagasari pisang bungkus daun pisang." },
    { id: 8, name: "Kue Talam", category: "Kue Basah", price: 26000, discountPrice: 22000, image: "", rating: 4.3, reviews: 14, description: "Kue talam pandan dan ketan hitam." },
    { id: 9, name: "Kue Bugis", category: "Kue Basah", price: 24000, discountPrice: 0, image: "", rating: 4.4, reviews: 16, description: "Kue bugis ketan isi unti kelapa." },
    { id: 10, name: "Kue Klepon", category: "Kue Basah", price: 18000, discountPrice: 15000, image: "", rating: 4.8, reviews: 35, description: "Klepon ketan hijau isi gula merah.", isPopular: true, isNew: true },
    { id: 11, name: "Kue Lapis Legit", category: "Kue Basah", price: 75000, discountPrice: 65000, image: "", rating: 4.9, reviews: 42, description: "Lapis legit premium 18 lapis, rempah pilihan.", isPopular: true },
    { id: 12, name: "Kue Dadar Gulung", category: "Kue Basah", price: 25000, discountPrice: 0, image: "", rating: 4.5, reviews: 22, description: "Dadar gulung pandan isi kelapa muda." },
    { id: 13, name: "Kue Cucur", category: "Kue Basah", price: 15000, discountPrice: 12000, image: "", rating: 4.6, reviews: 29, description: "Kue cucur gula merah khas Betawi." },
    { id: 14, name: "Kue Timphan Aceh", category: "Kue Basah", price: 35000, discountPrice: 30000, image: "", rating: 4.8, reviews: 33, description: "Kue timphan khas Aceh, isi pisang dan santan.", isNew: true },
    { id: 15, name: "Kue Lumpur Surga", category: "Kue Basah", price: 28000, discountPrice: 0, image: "", rating: 4.7, reviews: 24, description: "Kue lumpur surga pandan dengan lapisan legit." },
    { id: 16, name: "Nastar Keju", category: "Kue Kering", price: 45000, discountPrice: 38000, image: "", rating: 4.8, reviews: 45, description: "Nastar keju dengan selai nanas homemade.", isPopular: true },
    { id: 17, name: "Kastengel", category: "Kue Kering", price: 42000, discountPrice: 0, image: "", rating: 4.7, reviews: 38, description: "Kastengel keju edam parut, renyah dan gurih.", isPopular: true },
    { id: 18, name: "Putri Salju", category: "Kue Kering", price: 40000, discountPrice: 35000, image: "", rating: 4.6, reviews: 34, description: "Putri salju taburan gula halus, lumer di mulut." },
    { id: 19, name: "Lidah Kucing", category: "Kue Kering", price: 38000, discountPrice: 0, image: "", rating: 4.5, reviews: 28, description: "Lidah kucing renyah dengan berbagai rasa." },
    { id: 20, name: "Sagu Keju", category: "Kue Kering", price: 42000, discountPrice: 0, image: "", rating: 4.4, reviews: 21, description: "Sagu keju yang renyah dan gurih." },
    { id: 21, name: "Kue Semprong", category: "Kue Kering", price: 28000, discountPrice: 0, image: "", rating: 4.5, reviews: 25, description: "Kue semprong renyah khas tradisional." },
    { id: 22, name: "Kue Kacang", category: "Kue Kering", price: 35000, discountPrice: 0, image: "", rating: 4.6, reviews: 30, description: "Kue kacang tanah sangrai, renyah dan gurih." },
    { id: 23, name: "Dodol Ketan Hitam", category: "Kue Kering", price: 45000, discountPrice: 0, image: "", rating: 4.7, reviews: 36, description: "Dodol ketan hitam legit dan kenyal." },
    { id: 24, name: "Kue Semprit", category: "Kue Kering", price: 32000, discountPrice: 28000, image: "", rating: 4.4, reviews: 22, description: "Kue semprit bunga dengan taburan meses." },
    { id: 25, name: "Kue Bangket", category: "Kue Kering", price: 36000, discountPrice: 30000, image: "", rating: 4.3, reviews: 19, description: "Kue bangket kacang hijau, tekstur lembut." },
    { id: 26, name: "Wajik Ketan", category: "Kue Kering", price: 35000, discountPrice: 30000, image: "", rating: 4.4, reviews: 20, description: "Wajik ketan manis legit khas tradisional." },
    { id: 27, name: "Kue Mawar", category: "Kue Kering", price: 28000, discountPrice: 24000, image: "", rating: 4.5, reviews: 26, description: "Kue mawar renyah bentuk bunga." },
    { id: 28, name: "Dodol Aceh", category: "Kue Kering", price: 40000, discountPrice: 35000, image: "", rating: 4.7, reviews: 32, description: "Dodol khas Aceh legit dan manis.", isNew: true },
    { id: 29, name: "Rengginang", category: "Kue Kering", price: 20000, discountPrice: 17000, image: "", rating: 4.5, reviews: 24, description: "Rengginang ketan putih gurih." },
    { id: 30, name: "Lemper Ayam", category: "Kue Kering", price: 25000, discountPrice: 0, image: "", rating: 4.6, reviews: 28, description: "Lemper ayam suwir bungkus daun pisang." },
    { id: 31, name: "Keripik Singkong", category: "Keripik", price: 15000, discountPrice: 12000, image: "", rating: 4.5, reviews: 28, description: "Keripik singkong gurih renyah, pilihan rasa." },
    { id: 32, name: "Keripik Pisang", category: "Keripik", price: 13000, discountPrice: 0, image: "", rating: 4.4, reviews: 25, description: "Keripik pisang manis gurih." },
    { id: 33, name: "Keripik Tempe", category: "Keripik", price: 12000, discountPrice: 10000, image: "", rating: 4.7, reviews: 35, description: "Keripik tempe kriuk khas Indonesia.", isPopular: true },
    { id: 34, name: "Keripik Kentang", category: "Keripik", price: 18000, discountPrice: 15000, image: "", rating: 4.6, reviews: 31, description: "Keripik kentang tipis renyah original." },
    { id: 35, name: "Keripik Ubi", category: "Keripik", price: 15000, discountPrice: 0, image: "", rating: 4.3, reviews: 20, description: "Keripik ubi manis dan gurih." },
    { id: 36, name: "Keripik Bayam", category: "Keripik", price: 14000, discountPrice: 0, image: "", rating: 4.2, reviews: 15, description: "Keripik bayam renyah kaya nutrisi." },
    { id: 37, name: "Keripik Talas", category: "Keripik", price: 17000, discountPrice: 14000, image: "", rating: 4.5, reviews: 22, description: "Keripik talas khas Bogor." },
    { id: 38, name: "Keripik Usus", category: "Keripik", price: 20000, discountPrice: 0, image: "", rating: 4.6, reviews: 26, description: "Keripik usus ayam crispy." },
    { id: 39, name: "Keripik Kulit Ayam", category: "Keripik", price: 18000, discountPrice: 15000, image: "", rating: 4.7, reviews: 33, description: "Keripik kulit ayam krispi.", isPopular: true },
    { id: 40, name: "Keripik Melinjo", category: "Keripik", price: 16000, discountPrice: 0, image: "", rating: 4.2, reviews: 14, description: "Keripik melinjo (emping) gurih." },
    { id: 41, name: "Keripik Bawang", category: "Keripik", price: 13000, discountPrice: 10000, image: "", rating: 4.5, reviews: 27, description: "Keripik bawang gurih tradisional." },
    { id: 42, name: "Keripik Pare", category: "Keripik", price: 16000, discountPrice: 0, image: "", rating: 4.0, reviews: 9, description: "Keripik pare crunchy dengan bumbu spesial." },
    { id: 43, name: "Keripik Nangka", category: "Keripik", price: 18000, discountPrice: 0, image: "", rating: 4.3, reviews: 17, description: "Keripik nangka manis alami." },
    { id: 44, name: "Keripik Belut", category: "Keripik", price: 22000, discountPrice: 18000, image: "", rating: 4.4, reviews: 19, description: "Keripik belut gurih dan renyah." },
    { id: 45, name: "Keripik Sukun", category: "Keripik", price: 14000, discountPrice: 0, image: "", rating: 4.1, reviews: 11, description: "Keripik sukun renyah original." },
    { id: 46, name: "Pisang Goreng Crispy", category: "Snack", price: 15000, discountPrice: 12000, image: "", rating: 4.7, reviews: 34, description: "Pisang goreng crispy dengan topping coklat.", isPopular: true },
    { id: 47, name: "Bakso Goreng", category: "Snack", price: 25000, discountPrice: 0, image: "", rating: 4.6, reviews: 30, description: "Bakso goreng crispy isi daging sapi." },
    { id: 48, name: "Siomay Bandung", category: "Snack", price: 25000, discountPrice: 0, image: "", rating: 4.6, reviews: 29, description: "Siomay ikan tenggiri khas Bandung." },
    { id: 49, name: "Batagor", category: "Snack", price: 22000, discountPrice: 18000, image: "", rating: 4.7, reviews: 35, description: "Batagor ikan tenggiri dengan saus kacang." },
    { id: 50, name: "Pempek Palembang", category: "Snack", price: 35000, discountPrice: 30000, image: "", rating: 4.8, reviews: 38, description: "Pempek lenjer dan adaan khas Palembang.", isPopular: true },
    { id: 51, name: "Tahu Crispy", category: "Snack", price: 12000, discountPrice: 0, image: "", rating: 4.4, reviews: 22, description: "Tahu crispy renyah diluar lembut didalam." },
    { id: 52, name: "Tempe Mendoan", category: "Snack", price: 10000, discountPrice: 8000, image: "", rating: 4.5, reviews: 26, description: "Tempe mendoan khas Banyumas." },
    { id: 53, name: "Cireng Isi", category: "Snack", price: 18000, discountPrice: 0, image: "", rating: 4.3, reviews: 18, description: "Cireng isi ayam suwir pedas." },
    { id: 54, name: "Lumpia Semarang", category: "Snack", price: 28000, discountPrice: 0, image: "", rating: 4.5, reviews: 24, description: "Lumpia rebung khas Semarang." },
    { id: 55, name: "Martabak Mini", category: "Snack", price: 25000, discountPrice: 0, image: "", rating: 4.6, reviews: 27, description: "Martabak mini manis dengan topping." },
    { id: 56, name: "Pastel Goreng", category: "Snack", price: 20000, discountPrice: 17000, image: "", rating: 4.4, reviews: 21, description: "Pastel goreng isi bihun dan sayuran." },
    { id: 57, name: "Kroket Kentang", category: "Snack", price: 22000, discountPrice: 0, image: "", rating: 4.5, reviews: 23, description: "Kroket kentang isi daging dan sayuran." },
    { id: 58, name: "Risol Goreng", category: "Snack", price: 20000, discountPrice: 0, image: "", rating: 4.5, reviews: 25, description: "Risol goreng isi sayuran dan daging." },
    { id: 59, name: "Pukis Mini", category: "Snack", price: 18000, discountPrice: 15000, image: "", rating: 4.7, reviews: 32, description: "Pukis mini aneka topping.", isPopular: true },
    { id: 60, name: "Sosis Solo", category: "Snack", price: 28000, discountPrice: 24000, image: "", rating: 4.3, reviews: 16, description: "Sosis solo isi daging ayam cincang." },
    { id: 61, name: "Chocolate Chip Cookies", category: "Cookies", price: 35000, discountPrice: 30000, image: "", rating: 4.8, reviews: 40, description: "Cookies dengan dark chocolate chips premium.", isPopular: true },
    { id: 62, name: "Double Choco Cookies", category: "Cookies", price: 38000, discountPrice: 0, image: "", rating: 4.7, reviews: 36, description: "Double chocolate cookies lembut." },
    { id: 63, name: "Red Velvet Cookies", category: "Cookies", price: 38000, discountPrice: 0, image: "", rating: 4.6, reviews: 32, description: "Red velvet cookies dengan cream cheese." },
    { id: 64, name: "Matcha White Choco Cookies", category: "Cookies", price: 40000, discountPrice: 0, image: "", rating: 4.7, reviews: 34, description: "Matcha cookies dengan white chocolate." },
    { id: 65, name: "Peanut Butter Cookies", category: "Cookies", price: 32000, discountPrice: 28000, image: "", rating: 4.5, reviews: 28, description: "Cookies butter kacang renyah." },
    { id: 66, name: "Almond Cookies", category: "Cookies", price: 45000, discountPrice: 0, image: "", rating: 4.8, reviews: 38, description: "Almond cookies premium dengan kacang almond." },
    { id: 67, name: "Cranberry White Choco", category: "Cookies", price: 38000, discountPrice: 0, image: "", rating: 4.6, reviews: 29, description: "Cranberry cookies dengan white chocolate." },
    { id: 68, name: "Thumbprint Cookies", category: "Cookies", price: 35000, discountPrice: 0, image: "", rating: 4.5, reviews: 26, description: "Thumbprint cookies dengan selai strawberry." },
    { id: 69, name: "Shortbread Cookies", category: "Cookies", price: 30000, discountPrice: 26000, image: "", rating: 4.4, reviews: 21, description: "Shortbread cookies mentega klasik." },
    { id: 70, name: "Oatmeal Raisin Cookies", category: "Cookies", price: 32000, discountPrice: 0, image: "", rating: 4.4, reviews: 22, description: "Oatmeal cookies dengan kismis." },
    { id: 71, name: "Roti Tawar", category: "Roti", price: 18000, discountPrice: 15000, image: "", rating: 4.5, reviews: 27, description: "Roti tawar lembut kualitas premium." },
    { id: 72, name: "Roti Sobek", category: "Roti", price: 25000, discountPrice: 20000, image: "", rating: 4.6, reviews: 30, description: "Roti sobek empuk 5 rasa.", isPopular: true },
    { id: 73, name: "Roti Coklat", category: "Roti", price: 15000, discountPrice: 0, image: "", rating: 4.7, reviews: 33, description: "Roti isi coklat lumer." },
    { id: 74, name: "Roti Krim Keju", category: "Roti", price: 18000, discountPrice: 15000, image: "", rating: 4.5, reviews: 25, description: "Roti dengan filling cream cheese." },
    { id: 75, name: "Roti Sosis", category: "Roti", price: 18000, discountPrice: 0, image: "", rating: 4.6, reviews: 28, description: "Roti sosis dengan mayonaise." },
    { id: 76, name: "Roti Gandum", category: "Roti", price: 22000, discountPrice: 0, image: "", rating: 4.4, reviews: 22, description: "Roti gandum utuh kaya serat." },
    { id: 77, name: "Roti Kukus", category: "Roti", price: 12000, discountPrice: 10000, image: "", rating: 4.5, reviews: 26, description: "Roti kukus mekar lembut." },
    { id: 78, name: "Roti Kasur", category: "Roti", price: 35000, discountPrice: 0, image: "", rating: 4.7, reviews: 34, description: "Roti kasur super lembut ukuran besar." },
    { id: 79, name: "Roti Abon", category: "Roti", price: 20000, discountPrice: 0, image: "", rating: 4.4, reviews: 21, description: "Roti abon sapi premium." },
    { id: 80, name: "Roti Kentang", category: "Roti", price: 20000, discountPrice: 0, image: "", rating: 4.3, reviews: 19, description: "Roti kentang empuk dan gurih." },
    { id: 81, name: "Brownies Fudgy", category: "Brownies", price: 35000, discountPrice: 30000, image: "", rating: 4.8, reviews: 42, description: "Brownies fudgy premium coklat pekat.", isPopular: true },
    { id: 82, name: "Brownies Kukus", category: "Brownies", price: 28000, discountPrice: 0, image: "", rating: 4.7, reviews: 37, description: "Brownies kukus lembut dengan topping." },
    { id: 83, name: "Brownies Cheesecake", category: "Brownies", price: 45000, discountPrice: 0, image: "", rating: 4.9, reviews: 44, description: "Brownies cheesecake dengan lapisan cream cheese.", isPopular: true, isNew: true },
    { id: 84, name: "Brownies Almond", category: "Brownies", price: 40000, discountPrice: 35000, image: "", rating: 4.6, reviews: 31, description: "Brownies almond dengan kacang almond." },
    { id: 85, name: "Brownies Red Velvet", category: "Brownies", price: 38000, discountPrice: 0, image: "", rating: 4.7, reviews: 35, description: "Brownies red velvet cream cheese." },
    { id: 86, name: "Brownies Matcha", category: "Brownies", price: 38000, discountPrice: 32000, image: "", rating: 4.5, reviews: 27, description: "Brownies matcha dengan white chocolate." },
    { id: 87, name: "Blondies", category: "Brownies", price: 32000, discountPrice: 0, image: "", rating: 4.4, reviews: 22, description: "Blondies white chocolate cranberry." },
    { id: 88, name: "Brownies Ketan Hitam", category: "Brownies", price: 35000, discountPrice: 0, image: "", rating: 4.6, reviews: 30, description: "Brownies ketan hitam legit." },
    { id: 89, name: "Donat Glazed", category: "Donat", price: 12000, discountPrice: 10000, image: "", rating: 4.6, reviews: 30, description: "Donat glazed klasik dengan gula icing." },
    { id: 90, name: "Donat Coklat", category: "Donat", price: 15000, discountPrice: 0, image: "", rating: 4.7, reviews: 34, description: "Donat dengan topping coklat premium.", isPopular: true },
    { id: 91, name: "Donat Strawberry", category: "Donat", price: 15000, discountPrice: 12000, image: "", rating: 4.5, reviews: 26, description: "Donat topping strawberry manis." },
    { id: 92, name: "Donat Matcha", category: "Donat", price: 18000, discountPrice: 0, image: "", rating: 4.6, reviews: 28, description: "Donat green tea matcha." },
    { id: 93, name: "Donat Keju", category: "Donat", price: 16000, discountPrice: 0, image: "", rating: 4.4, reviews: 22, description: "Donat taburan keju parut." },
    { id: 94, name: "Donat Isi Coklat", category: "Donat", price: 18000, discountPrice: 15000, image: "", rating: 4.7, reviews: 32, description: "Donat isi coklat lumer." },
    { id: 95, name: "Donat Kentang", category: "Donat", price: 12000, discountPrice: 10000, image: "", rating: 4.5, reviews: 25, description: "Donat kentang empuk dan lembut." },
    { id: 96, name: "Donat Ubi Ungu", category: "Donat", price: 15000, discountPrice: 0, image: "", rating: 4.4, reviews: 20, description: "Donat ubi ungu natural.", isNew: true },
    { id: 97, name: "Bolu Pandan", category: "Bolu", price: 30000, discountPrice: 25000, image: "", rating: 4.6, reviews: 29, description: "Bolu pandan lembut wangi pandan asli." },
    { id: 98, name: "Bolu Tape Keju", category: "Bolu", price: 32000, discountPrice: 0, image: "", rating: 4.5, reviews: 24, description: "Bolu tape singkong keju." },
    { id: 99, name: "Bolu Kukus Mekar", category: "Bolu", price: 25000, discountPrice: 20000, image: "", rating: 4.7, reviews: 33, description: "Bolu kukus mekar aneka warna." },
    { id: 100, name: "Bolu Gulung", category: "Bolu", price: 28000, discountPrice: 0, image: "", rating: 4.5, reviews: 26, description: "Bolu gulung isi selai strawberry." },
    { id: 101, name: "Bolu Coklat", category: "Bolu", price: 35000, discountPrice: 30000, image: "", rating: 4.7, reviews: 31, description: "Bolu coklat dengan meses." },
    { id: 102, name: "Bolu Keju", category: "Bolu", price: 38000, discountPrice: 0, image: "", rating: 4.4, reviews: 21, description: "Bolu keju dengan taburan keju parut." },
    { id: 103, name: "Bolu Pisang", category: "Bolu", price: 28000, discountPrice: 24000, image: "", rating: 4.6, reviews: 27, description: "Bolu pisang ambon matang." },
    { id: 104, name: "Bolu Karamel", category: "Bolu", price: 32000, discountPrice: 0, image: "", rating: 4.5, reviews: 24, description: "Bolu karamel sarang semut." },
    { id: 105, name: "Bolu Ketan Hitam", category: "Bolu", price: 35000, discountPrice: 0, image: "", rating: 4.5, reviews: 23, description: "Bolu ketan hitam legit." },
    { id: 106, name: "Paket Oleh-Oleh Kecil", category: "Oleh-Oleh", price: 50000, discountPrice: 45000, image: "", rating: 4.7, reviews: 35, description: "Paket oleh-oleh berisi 3 kue pilihan.", isNew: true },
    { id: 107, name: "Paket Oleh-Oleh Besar", category: "Oleh-Oleh", price: 85000, discountPrice: 75000, image: "", rating: 4.8, reviews: 38, description: "Paket oleh-oleh besar berisi 6 kue pilihan." },
    { id: 108, name: "Kue Kering Toples", category: "Oleh-Oleh", price: 65000, discountPrice: 0, image: "", rating: 4.6, reviews: 30, description: "Toples kue kering premium campur." },
    { id: 109, name: "Paket Camilan Keripik", category: "Oleh-Oleh", price: 35000, discountPrice: 30000, image: "", rating: 4.5, reviews: 25, description: "Paket camilan keripik campur." },
    { id: 110, name: "Kue Basah Bingkisan", category: "Oleh-Oleh", price: 55000, discountPrice: 0, image: "", rating: 4.6, reviews: 28, description: "Bingkisan kue basah pilihan." },
    { id: 111, name: "Sale Pisang", category: "Oleh-Oleh", price: 30000, discountPrice: 0, image: "", rating: 4.4, reviews: 22, description: "Sale pisang manis legit." },
    { id: 112, name: "Keripik Singkong Aceh", category: "Oleh-Oleh", price: 25000, discountPrice: 20000, image: "", rating: 4.5, reviews: 26, description: "Keripik singkong khas Aceh pedas gurih." },
    { id: 113, name: "Hampers Lebaran Kecil", category: "Hampers", price: 100000, discountPrice: 85000, image: "", rating: 4.8, reviews: 40, description: "Hampers lebaran berisi 3 toples kue kering.", isPopular: true },
    { id: 114, name: "Hampers Lebaran Besar", category: "Hampers", price: 175000, discountPrice: 150000, image: "", rating: 4.9, reviews: 45, description: "Hampers lebaran premium 5 toples + kue basah.", isPopular: true },
    { id: 115, name: "Hampers Ulang Tahun", category: "Hampers", price: 125000, discountPrice: 100000, image: "", rating: 4.7, reviews: 36, description: "Hampers ulang tahun dengan dekorasi cantik." },
    { id: 116, name: "Hampers Pernikahan", category: "Hampers", price: 200000, discountPrice: 175000, image: "", rating: 4.9, reviews: 42, description: "Hampers pernikahan premium elegan." },
    { id: 117, name: "Hampers Natal", category: "Hampers", price: 150000, discountPrice: 125000, image: "", rating: 4.7, reviews: 33, description: "Hampers natal dengan tema merah hijau.", isNew: true },
    { id: 118, name: "Hampers Syukuran", category: "Hampers", price: 135000, discountPrice: 110000, image: "", rating: 4.6, reviews: 30, description: "Hampers untuk acara syukuran." },
    { id: 119, name: "Kue Lapis", category: "Traditional Cake", price: 25000, discountPrice: 20000, image: "", rating: 4.5, reviews: 23, description: "Kue lapis legit 8 lapisan." },
    { id: 120, name: "Kue Klepon", category: "Traditional Cake", price: 18000, discountPrice: 15000, image: "", rating: 4.8, reviews: 35, description: "Klepon ketan hijau isi gula merah." },
    { id: 121, name: "Kue Cucur", category: "Traditional Cake", price: 15000, discountPrice: 12000, image: "", rating: 4.6, reviews: 29, description: "Kue cucur gula merah khas Betawi." },
    { id: 122, name: "Kue Timphan", category: "Traditional Cake", price: 35000, discountPrice: 30000, image: "", rating: 4.8, reviews: 33, description: "Kue timphan khas Aceh." },
    { id: 123, name: "Kue Lapis Legit", category: "Traditional Cake", price: 75000, discountPrice: 65000, image: "", rating: 4.9, reviews: 42, description: "Lapis legit premium 18 lapis." },
    { id: 124, name: "Dodol Aceh", category: "Traditional Cake", price: 40000, discountPrice: 35000, image: "", rating: 4.7, reviews: 32, description: "Dodol khas Aceh." },
    { id: 125, name: "Brownies Cheesecake", category: "Modern Cake", price: 45000, discountPrice: 0, image: "", rating: 4.9, reviews: 44, description: "Brownies cheesecake premium." },
    { id: 126, name: "Red Velvet Cake", category: "Modern Cake", price: 55000, discountPrice: 48000, image: "", rating: 4.8, reviews: 38, description: "Red velvet cake cream cheese frosting.", isPopular: true, isNew: true },
    { id: 127, name: "Chocolate Moist Cake", category: "Modern Cake", price: 50000, discountPrice: 0, image: "", rating: 4.7, reviews: 35, description: "Chocolate moist cake premium." },
    { id: 128, name: "Cheesecake", category: "Modern Cake", price: 60000, discountPrice: 52000, image: "", rating: 4.8, reviews: 40, description: "New York style cheesecake." },
    { id: 129, name: "Tiramisu", category: "Modern Cake", price: 65000, discountPrice: 0, image: "", rating: 4.7, reviews: 36, description: "Tiramisu Italian dessert." },
    { id: 130, name: "Lemon Cake", category: "Modern Cake", price: 45000, discountPrice: 0, image: "", rating: 4.5, reviews: 28, description: "Lemon cake segar dengan frosting." },
    { id: 131, name: "Carrot Cake", category: "Modern Cake", price: 48000, discountPrice: 42000, image: "", rating: 4.6, reviews: 32, description: "Carrot cake walnut cream cheese." },
    { id: 132, name: "Black Forest", category: "Modern Cake", price: 55000, discountPrice: 0, image: "", rating: 4.7, reviews: 34, description: "Black forest classic dengan cherry." },
    { id: 133, name: "Opera Cake", category: "Modern Cake", price: 70000, discountPrice: 0, image: "", rating: 4.6, reviews: 29, description: "Opera cake French dessert." },
    { id: 134, name: "Mango Cake", category: "Modern Cake", price: 50000, discountPrice: 0, image: "", rating: 4.7, reviews: 33, description: "Mango cake dengan mango mousse." },
    { id: 135, name: "Strawberry Shortcake", category: "Modern Cake", price: 52000, discountPrice: 45000, image: "", rating: 4.6, reviews: 31, description: "Strawberry shortcake dengan whipped cream." },
    { id: 136, name: "Chocolate Tower", category: "Modern Cake", price: 85000, discountPrice: 75000, image: "", rating: 4.9, reviews: 43, description: "Chocolate tower cake 3 tingkat premium." },
    { id: 137, name: "Rainbow Cake", category: "Modern Cake", price: 48000, discountPrice: 0, image: "", rating: 4.5, reviews: 27, description: "Rainbow cake 6 warna cerah." },
    { id: 138, name: "Blueberry Cheesecake", category: "Modern Cake", price: 58000, discountPrice: 50000, image: "", rating: 4.7, reviews: 35, description: "Blueberry cheesecake dengan topping blueberry." },
    { id: 139, name: "Matcha Layer Cake", category: "Modern Cake", price: 52000, discountPrice: 0, image: "", rating: 4.6, reviews: 30, description: "Matcha layer cake dengan red bean." },
    { id: 140, name: "Bolu Kukus Splash", category: "Modern Cake", price: 28000, discountPrice: 24000, image: "", rating: 4.5, reviews: 26, description: "Bolu kukus splash warna-warni." }
];

const categories = [
    { name: "Kue Basah", icon: "fa-cake-candles", count: 16 },
    { name: "Kue Kering", icon: "fa-cookie-bite", count: 15 },
    { name: "Keripik", icon: "fa-chips", count: 15, alt: "fa-seedling" },
    { name: "Snack", icon: "fa-pizza-slice", count: 15 },
    { name: "Cookies", icon: "fa-cookie", count: 10 },
    { name: "Roti", icon: "fa-bread-slice", count: 10 },
    { name: "Brownies", icon: "fa-square", count: 8 },
    { name: "Donat", icon: "fa-circle", count: 8 },
    { name: "Bolu", icon: "fa-cake", count: 9 },
    { name: "Oleh-Oleh", icon: "fa-gift", count: 7 },
    { name: "Hampers", icon: "fa-gem", count: 6 },
    { name: "Traditional Cake", icon: "fa-flag", count: 6, label: "Kue Tradisional" },
    { id: 13, name: "Kue Modern", slug: "modern-cake", icon: "fa-star", count: 15 }
];

const testimonials = [
    { name: "Siti Rahmawati", role: "Pelanggan Setia", text: "Kue dari Dapur Mulia selalu fresh dan enak. Nastarnya terbaik di Aceh! Recommended banget.", rating: 5 },
    { name: "Muhammad Faisal", role: "Pelanggan Baru", text: "Beli hampers lebaran di sini, kualitas premium dan packaging cantik. Pasti repeat order!", rating: 5 },
    { name: "Dewi Sartika", role: "Ibu Rumah Tangga", text: "Brownies fudgy-ya bikin nagih. Anak-anak suka semua kue dari Dapur Mulia.", rating: 5 },
    { name: "Rizki Ananda", role: "Mahasiswa", text: "Pesen kue buat ulang tahun teman, fresh dan manisnya pas. Harga terjangkau!", rating: 4 },
    { name: "Nurul Aini", role: "Guru", text: "Kue tradisionalnya bikin kangen masa kecil. Kualitasnya terjaga dan selalu konsisten.", rating: 5 },
    { name: "Teuku Irfan", role: "Pengusaha", text: "Oleh-oleh buat kolega dari luar kota, semua suka. Dodol Aceh-nya top!", rating: 5 }
];
